name: Data Pipeline Production

on: [push]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment Variables
        run: |
          echo "MINIO_USER=${{ secrets.MINIO_USER }}" >> .env
          echo "MINIO_PASSWORD=${{ secrets.MINIO_PASSWORD }}" >> .env

      - name: Run Pipeline via Docker Compose
        run: |
          docker compose up --build --exit-code-from app

      - name: Cleanup
        if: always()
        run: docker compose down -v