name: Data Pipeline Production

on: [push]

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Start Infrastructure with Docker Compose
        run: |
          export MINIO_USER=${{ secrets.MINIO_USER }}
          export MINIO_PASSWORD=${{ secrets.MINIO_PASSWORD }}
        
          docker-compose up -d minio createbuckets
        
          docker wait financial_pipeline-createbuckets-1 || true

      - name: Build and Run App
        run: |
          export MINIO_USER=${{ secrets.MINIO_USER }}
          export MINIO_PASSWORD=${{ secrets.MINIO_PASSWORD }}
          
          docker-compose up --build --exit-code-from app app